apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jithendar/frontend:10.5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   labels:
#     app: frontend
#     project: roboshop
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#       project: roboshop
#   template:
#     metadata:
#       labels:
#         app: frontend
#         project: roboshop
#     spec:
#       containers:
#       - name: frontend
#         image: jithendar/frontend:10.5
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontend
# spec: 
#   type: LoadBalancer
#   selector: 
#     app: roboshop
#   ports:
#     - port: 80
#       name: tcp
#       targetPort: 80

