apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nginx
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      project: roboshop
  template:
    metadata:
      labels:
        app: frontend
        project: roboshop
    spec:
      containers:
      - name: frontend
        image: jithendar/fronetned:IMAGETAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    app: nginx
  ports: TCP
  port: 80
  targetPort: 80

