apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nginx
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      project: roboshop
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
    spec:
      containers:
      - name: frontend
        image: jithendar/fronetned:IMAGETAG
        resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadate: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    app: nginx
  ports:
  - portocol: TCP 
    port: 80
    targetPort: 80

